extends:
  - prettier
  - plugin:import/errors
  - plugin:import/warnings
  - eslint:recommended
env:
  node: true
  es6: true
  jest: true
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 7
  sourceType: module
plugins:
  - prettier
rules:
  no-empty: warn
  no-console: 2
  camelcase: 2
  comma-spacing: 2
  comma-style: 0
  semi: 2
  prettier/prettier:
    - "error"
  import/no-extraneous-dependencies:
    - "error"
    - devDependencies: false
  import/prefer-default-export: 0
